In [75]:
import pysheaf as ps
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import matrix_rank

In [82]:
## From p. 98 Example 4.9:

## Restriction Maps:
restAD = np.matrix([1,0,0,0])
restAG = np.matrix([0,0,1,-1])
restBD = np.matrix([1,0,0])
restBE = np.matrix([[0,0,3],[0,2,0]])
restBF = np.matrix([0,1,0])
restCE = np.matrix([[0,0,3,0],[0,0,0,2]])
restCF = np.matrix([0,0,0,1])
restCG = np.matrix([1,-1,0,0])

cofaceAD = ps.SheafCoface(3,1,restAD)
cofaceAG = ps.SheafCoface(6,1,restAG)
cofaceBD = ps.SheafCoface(3,-1,restBD)
cofaceBE = ps.SheafCoface(4,1,restBE)
cofaceBF = ps.SheafCoface(5,1,restBF)
cofaceCE = ps.SheafCoface(4,-1,restCE)
cofaceCF = ps.SheafCoface(5,-1,restCF)
cofaceCG = ps.SheafCoface(6,-1,restCG)

cellA = ps.SheafCell(dimension=0,id=0,stalkDim=4,name='A',
                     cofaces=[cofaceAD,cofaceAG])
cellB = ps.SheafCell(dimension=0,id=1,stalkDim=3,name='B',
                     cofaces=[cofaceBD,cofaceBE,cofaceBF])
cellC = ps.SheafCell(dimension=0,id=2,stalkDim=4,name='C',
                     cofaces=[cofaceCE,cofaceCF,cofaceCG])
cellD = ps.SheafCell(dimension=1,id=3,stalkDim=1,name='D')
cellE = ps.SheafCell(dimension=1,id=4,stalkDim=2,name='E')
cellF = ps.SheafCell(dimension=1,id=5,stalkDim=1,name='F')
cellG = ps.SheafCell(dimension=1,id=6,stalkDim=1,name='G')

sheaf = ps.Sheaf([cellA,cellB,cellC,cellD,cellE,cellF,cellG])


In [83]:
print isinstance(cofaceAD,ps.SheafCoface)

True


In [84]:
print cofaceAD.isLinear()

print cellA.isLinear()

True
True


In [85]:
print cellA.isNumeric()


True


In [86]:
for coface in sheaf.cofaces(0):  ### id=0 references cellA
    print coface

(index=3,orientation=1,restriction=[[1 0 0 0]])
(index=6,orientation=1,restriction=[[ 0  0  1 -1]])


In [87]:
### This cell and the next illustrate a problem with current indexing. 
### The resulting coface indices have no relationship to the original sheaf

star = sheaf.star([0]) 
print star.cells

[(dimension=0,compactClosure=True,(index=1,orientation=1,restriction=[[1 0 0 0]]),(index=2,orientation=1,restriction=[[ 0  0  1 -1]])), (dimension=1,compactClosure=False,stalkdim=1), (dimension=1,compactClosure=False,stalkdim=1)]


In [88]:
star = sheaf.star([1])
print star.cells

[(dimension=0,compactClosure=True,(index=1,orientation=-1,restriction=[[1 0 0]]),(index=2,orientation=1,restriction=[[0 0 3]
 [0 2 0]]),(index=3,orientation=1,restriction=[[0 1 0]])), (dimension=1,compactClosure=False,stalkdim=1), (dimension=1,compactClosure=False,stalkdim=2), (dimension=1,compactClosure=False,stalkdim=1)]


In [89]:
sheaf.kcells(0)   ## what is output supposed to be here?

([0, 1, 2], [4, 3, 4], [0, 4, 7, 11])

In [124]:
sheaf.coboundary(0)

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  3.+0.j,
         0.+0.j,  0.+0.j, -3.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  2.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j, -2.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        -1.+0.j,  1.+0.j,  0.+0.j,  0.+0.j]])

In [125]:
sheaf.cohomology(0)

array([[  0.00000000e+00-0.j,  -2.88675135e-01-0.j,   0.00000000e+00-0.j,
          4.08248290e-01-0.j,  -4.08248290e-01-0.j,   0.00000000e+00-0.j,
          2.88675135e-01-0.j],
       [  0.00000000e+00-0.j,   0.00000000e+00-0.j,  -7.07106781e-01-0.j,
          0.00000000e+00-0.j,   0.00000000e+00-0.j,   7.07106781e-01-0.j,
          0.00000000e+00-0.j],
       [ -8.66025404e-01-0.j,   0.00000000e+00-0.j,   0.00000000e+00-0.j,
         -7.85046229e-17-0.j,   7.85046229e-17-0.j,   0.00000000e+00-0.j,
          0.00000000e+00-0.j],
       [ -2.88675135e-01-0.j,  -4.71404521e-01-0.j,   0.00000000e+00-0.j,
         -3.33333333e-01-0.j,   3.33333333e-01-0.j,   0.00000000e+00-0.j,
          4.71404521e-01-0.j],
       [  0.00000000e+00-0.j,  -2.88675135e-01-0.j,   0.00000000e+00-0.j,
          4.08248290e-01-0.j,  -4.08248290e-01-0.j,   0.00000000e+00-0.j,
          2.88675135e-01-0.j],
       [  9.61481343e-17-0.j,   5.00000000e-01-0.j,   0.00000000e+00-0.j,
          1.23259516e-32-0.j,  

In [93]:
sheaf.coboundary(0).shape[1] - matrix_rank(sheaf.coboundary(0))

7

In [105]:
sheaf.coboundary(0) == sheaf.coboundary(0).astype(int)

/opt/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  if __name__ == '__main__':


array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True]], dtype=bool)

In [106]:
sheaf.coboundary(0).astype(int)

/opt/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  if __name__ == '__main__':


array([[ 1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  0,  0, -3,  0],
       [ 0,  0,  0,  0,  0,  2,  0,  0,  0,  0, -2],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0, -1],
       [ 0,  0,  1, -1,  0,  0,  0, -1,  1,  0,  0]])

In [110]:
np.sum(sheaf.coboundary(0) == np.array([[ 1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  0,  0, -3,  0],
       [ 0,  0,  0,  0,  0,  2,  0,  0,  0,  0, -2],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0, -1],
       [ 0,  0,  1, -1,  0,  0,  0, -1,  1,  0,  0]]) )

55

In [127]:
m,n = sheaf.coboundary(0).shape;m*n

55

In [130]:
 = matrix_rank(d)
print n - r

7


In [132]:
sheaf.betti(0)

7